version: "3"
services:
  nginx_cacti:
    restart: always
    image: nginx:cacti
    container_name: nginx_cacti
    volumes:
       - /etc/localtime:/etc/localtime
       - /etc/timezone:/etc/timezone
       - $PWD/cacti:/usr/local/Nginx/html/cacti
       - ./nginx.conf:/usr/local/Nginx/conf/nginx.conf
    privileged: true
    links:
       - php_cacti
    ports:
       - 80:80
  php_cacti:
    restart: always
    image: php:cacti
    container_name: php_cacti
    volumes:
       - /etc/localtime:/etc/localtime
       - /etc/timezone:/etc/timezone
       - ./cacti:/usr/local/Nginx/html/cacti
       - ./php-fpm.conf:/usr/local/php/etc/php-fpm.conf
       - ./php.ini:/usr/local/php/etc/php.ini
       - ./snmpd.conf:/etc/snmp/snmpd.conf
       - ./spine.conf:/etc/spine.conf
    privileged: true
    links:
       - mysql_cacti
    expose:
       - 9000
  mysql_cacti:
    restart: always
    image: mysql:cacti
    container_name: mysql_cacti
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - $PWD/mysql:/var/lib/mysql
      - $PWD/secure:/var/lib/mysql-files
      - $PWD/my.cnf:/etc/my.cnf
      - $PWD/general.log:/var/log/mysql/general.log
      - $PWD/error.log:/var/log/mysql/error.log
      - ./cacti:/usr/local/Nginx/html/cacti
    ports:
      - 33066:3306
