#!/bin/bash

# 添加cacti目录
cd container
tar zvxf cacti-1.1.38.tar.gz && mv cacti-1.1.38 cacti
sed -i '/database_hostname/s/localhost/mysql_cacti/g' cacti/include/config.php
sed -i '/database_password/s/cactiuser/cactipassword/g' cacti/include/config.php
chmod 777 *.log

# 启动容器
docker-compose up -d

sleep 30

# 配置cacti数据库
docker exec mysql_cacti mysql -uroot -plinuxwt123 -e "create database cacti;use cacti;source /usr/local/Nginx/html/cacti/cacti.sql;create user 'cactiuser'@'%' identified by 'cactipassword';create user 'cactiuser'@'localhost' identified by 'cactipassword';grant all on *.* to root;grant all on cacti.* to root@localhost;grant all on cacti.* to cactiuser;grant all on cacti.* to cactiuser@localhost;flush privileges;grant select on mysql.time_zone_name to cactiuser@'%';"
docker cp bug.sh $(docker ps -a | grep mysql_cacti | awk '{print $1}'):/tmp
docker exec mysql_cacti chmod +x /tmp/bug.sh
docker exec mysql_cacti /tmp/bug.sh 
echo "*/1 * * * * root /usr/bin/bash $(pwd)/poller.sh" >> /etc/crontab && systemctl restart crond
