FROM centos:7
MAINTAINER linuxwt <tengwanginit@gmail.com>

# 更换163源
RUN yum -y install wget
RUN cd /etc/yum.repos.d \
&&  mv CentOS-Base.repo CentOS-Base.repo.bak \
&& wget  http://mirrors.163.com/.help/CentOS7-Base-163.repo \
&& mv CentOS7-Base-163.repo CentOS-Base.repo \
&& yum makecache 


# 配置相关的依赖
RUN yum -y install gcc gcc-c++ \
&&  yum -y install pcre* \
&&  yum -y install zlib* \
&&  yum -y install make

RUN yum -y install pango*
RUN yum -y install perl-devel
RUN yum -y install libxml2 libxml2-devel

# 将宿主机解压后的源码包添加进来,然后编译安装
ADD nginx-1.15.5.tar.gz /tmp
RUN mkdir -p /usr/local/Nginx \
&& cd /tmp/nginx-1.15.5  && ./configure --prefix=/usr/local/Nginx --with-poll_module --with-http_stub_status_module && make && make install \
&& echo "daemon off;" >> /usr/local/Nginx/conf/nginx.conf

expose 80
CMD ["/usr/local/Nginx/sbin/nginx"]  
